name: influxdb-ijohnson
version: '1.5.1'
summary: An Open-Source Time Series Database
description: |
  InfluxDB is an open source time series database with no external dependencies.
  It's useful for recording metrics, events, and performing analytics.

grade: stable
confinement: strict

parts:
  scripts:
    source: scripts
    plugin: dump
    organize:
      '*.sh': bin/
    prime:
      - bin
  go:
    source-tag: go1.9.5
    source-depth: 1
  influxdb:
    after: [go]
    source: https://github.com/influxdata/influxdb.git
    source-tag: v1.5.1
    source-depth: 1
    plugin: python
    install: |
      #
    build: |
      export PATH="$SNAPCRAFT_STAGE/bin:$PATH"
      export GOPATH=$(readlink -f $(pwd)/../go)
      export GOIMPORTPATH=$GOPATH/src/github.com/influxdata/influxdb/
      mkdir -p $GOIMPORTPATH
      cp -r ./* $GOIMPORTPATH
      cd $GOIMPORTPATH
      python build.py --outdir $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/conf
      cp etc/config.sample.toml $SNAPCRAFT_PART_INSTALL/conf/influxdb.conf
    stage-packages:
      - libdb5.3-dev
    build-packages: 
      - python-software-properties
      - software-properties-common
      - wget
      - git
      - mercurial
      - make
      - ruby
      - ruby-dev
      - autoconf
      - libtool
      - build-essential
      - rpm
      - zip
      - python
      - python-boto
      - asciidoc
      - xmlto
      - docbook-xsl


apps:
  influx:
    command: bin/influx
    plugs:
      - network
  influxd:
    command: bin/runinfluxd.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - network